# -----------------------------------
# This file is generated by Docker.sh
# -----------------------------------

DOCKER_UID=1000

if getent passwd $DOCKER_UID; then
	echo "User $DOCKER_UID exists in /etc/passwd so use them as DOCKER_USER"
else
	groupadd --gid $DOCKER_UID dockeruser
	useradd --uid $DOCKER_UID --gid dockeruser --shell /bin/bash --create-home dockeruser
fi

DOCKER_USER=$(id -nu $DOCKER_UID)

echo "DOCKER_UID = $DOCKER_UID"
echo "DOCKER_USER = $DOCKER_USER"

usermod -a -G $DOCKER_USER root
usermod -a -G root $DOCKER_USER
