#!/usr/bin/env bash


## Injector hack, make user in container with same id as host user
# create UID injector
# This thing make all files accesible between container's and host and is executed on create with Dockerfile
injector() {

	APP=$1

	echo "[Injector] Create for '$APP' with UID '${UID}'"

	{
		echo "#!/usr/bin/env bash" > $DIR/_docker/$1/injector.sh
		echo "# -----------------------------------"
		echo "# This file is generated by Docker.sh"
		echo "# -----------------------------------"
		echo ""
		echo "DOCKER_UID=$UID"
		echo ""
		echo "if getent passwd \$DOCKER_UID; then"
		echo "	echo \"User \$DOCKER_UID exists in /etc/passwd so use them as DOCKER_USER\""
		echo "else"
		echo "	groupadd --gid \$DOCKER_UID dockeruser"
		echo "	useradd --uid \$DOCKER_UID --gid dockeruser --shell /bin/bash --create-home dockeruser"
		echo "fi"
		echo ""
		echo "DOCKER_USER=\$(id -nu \$DOCKER_UID)"
		echo ""
		echo "echo \"DOCKER_UID = \$DOCKER_UID\""
		echo "echo \"DOCKER_USER = \$DOCKER_USER\""
		echo ""
		for i in ${*:2} #or use $@
		do
		  echo "usermod -a -G \$DOCKER_USER $i"
		  echo "usermod -a -G $i \$DOCKER_USER"
		done
	} > $DIR/_docker/$APP/injector.sh

}
